# Generated by Django 5.2.6 on 2025-09-21 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('pausa', 'Pausa'), ('retorno', 'Retorno'), ('saida', 'Saída')], max_length=20)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ATRASO', 'Atraso'), ('FALTA', 'Falta')], default='OK', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
